type State =
  | 'AndhraPradesh'
  | 'ArunachalPradesh'
  | 'Assam'
  | 'Bihar'
  | 'Chhattisgarh'
  | 'Goa'
  | 'Gujarat'
  | 'Haryana'
  | 'HimachalPradesh'
  | 'JammuAndKashmir'
  | 'Jharkhand'
  | 'Karnataka'
  | 'Kerala'
  | 'MadhyaPradesh'
  | 'Maharashtra'
  | 'Manipur'
  | 'Meghalaya'
  | 'Mizoram'
  | 'Nagaland'
  | 'Odisha'
  | 'Punjab'
  | 'Rajasthan'
  | 'Sikkim'
  | 'TamilNadu'
  | 'Telangana'
  | 'Tripura'
  | 'Uttarakhand'
  | 'UttarPradesh'
  | 'WestBengal'
  | 'AndamanAndNicobarIslands'
  | 'DadraAndNagarHaveli'
  | 'DamanAndDiu'
  | 'Delhi'
  | 'Lakshadweep'
  | 'Puducherry';

export const Constant = {
  // List of states
  states: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttarakhand',
    'Uttar Pradesh',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Dadra and Nagar Haveli',
    'Daman and Diu',
    'Delhi',
    'Lakshadweep',
    'Puducherry',
  ],

  // Cities for each state
  cities: {
    AndhraPradesh: [
      'Amaravati',
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Kurnool',
      'Nellore',
      'Rajahmundry',
      'Tirupati',
      'Anantapur',
      'Chittoor',
      'Srikakulam',
      'Kadapa',
      'Khammam',
      'Karimnagar',
      'Warangal',
      'Eluru',
      'Machilipatnam',
      'Nandyal',
      'Bhimavaram',
      'Proddatur',
      'Madanapalle',
      'Bapatla',
      'Kakinada',
      'Peddapuram',
      'Tanuku',
      'Chirala',
      'Markapur',
      'Tadepalligudem',
      'Palnadu',
      'Jammalamadugu',
    ],
    ArunachalPradesh: [
      'Itanagar', // Capital city
      'Tawang',
      'Ziro',
      'Pasighat',
      'Naharlagun',
      'Tezpur',
      'Bomdila',
      'Aalo',
      'Roing',
      'Changlang',
      'Namsai',
      'Yingkiong',
      'Anini',
      'Daporijo',
      'Seppa',
      'Lohit',
      'Miao',
      'Khonsa',
      'Rajiv Gandhi University (Doimukh)',
      'Menechukha',
      'Tirap',
      'West Kameng',
      'East Siang',
      'Upper Subansiri',
    ],
    Assam: [
      'Dispur', // Capital city
      'Guwahati', // Largest city
      'Dibrugarh',
      'Jorhat',
      'Silchar',
      'Tinsukia',
      'Nagaon',
      'Bongaigaon',
      'Tezpur',
      'Nalbari',
      'Golaghat',
      'Haflong',
      'Barpeta',
      'Sivasagar',
      'Karimganj',
      'Cachar',
      'Morigaon',
      'Kokrajhar',
      'Dhubri',
      'Kamrup',
      'Bongaigaon',
      'Hojai',
      'Lakhimpur',
      'Majuli',
      'Chirang',
      'Sonitpur',
      'Dhemaji',
      'Barpeta',
      'Bilasipara',
    ],
    Bihar: [
      'Patna', // Capital city
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Darbhanga',
      'Munger',
      'Purnea',
      'Arrah',
      'Chhapra',
      'Begusarai',
      'Sasaram',
      'Samastipur',
      'Nalanda',
      'Siwan',
      'Bihar Sharif',
      'Motihari',
      'Jamui',
      'Sitamarhi',
      'Khagaria',
      'Buxar',
      'Lakhisarai',
      'Katihar',
      'Madhepura',
      'Vaishali',
      'Kishanganj',
      'Bagaha',
      'Forbesganj',
      'Sheikhpura',
      'Jehanabad',
      'Kaimur',
      'Rohtas',
      'Saran',
    ],
    Chhattisgarh: [
      'Raipur', // Capital city
      'Bilaspur',
      'Durg',
      'Korba',
      'Raigarh',
      'Jagdalpur',
      'Ambikapur',
      'Rajnandgaon',
      'Bhilai',
      'Kawardha',
      'Mahasamund',
      'Dhamtari',
      'Surguja',
      'Janjgir-Champa',
      'Bemetara',
      'Balod',
      'Mungeli',
      'Jashpur',
      'Kanker',
      'Narayanpur',
      'Bijapur',
      'Sarguja',
      'Kondagaon',
      'Baloda Bazar',
      'Raigarh',
      'Pali',
    ],
    Goa: [
      'Panaji', // Capital city
      'Vasco da Gama',
      'Margao',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Cortalim',
      'Quepem',
      'Canacona',
      'Cavelossim',
      'Aldona',
      'Assolna',
      'Sanguem',
      'Taleigao',
      'Aquem',
      'Siridao',
      'Dona Paula',
    ],
    Gujarat: [
      'Gandhinagar', // Capital city
      'Ahmedabad', // Largest city
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Anand',
      'Nadiad',
      'Vapi',
      'Junagadh',
      'Mehsana',
      'Navsari',
      'Veraval',
      'Morbi',
      'Bharuch',
      'Daman',
      'Porbandar',
      'Bharuch',
      'Narmada',
      'Gandhidham',
      'Bhuj',
      'Godhra',
      'Himmatnagar',
      'Wadhwan',
      'Modasa',
      'Patan',
      'Unjha',
      'Kheda',
      'Valsad',
    ],
    Haryana: [
      'Chandigarh', // Capital city (shared with Punjab)
      'Gurugram', // Gurgaon
      'Faridabad',
      'Karnal',
      'Ambala',
      'Panipat',
      'Hisar',
      'Rohtak',
      'Sonipat',
      'Yamunanagar',
      'Sirsa',
      'Fatehabad',
      'Bhiwani',
      'Mahendragarh',
      'Rewari',
      'Palwal',
      'Jind',
      'Kaithal',
      'Narnaul',
      'Tosham',
      'Narwana',
      'Pehowa',
      'Safidon',
      'Hansi',
      'Bahadurgarh',
      'Barwala',
      'Kharkhoda',
    ],
    HimachalPradesh: [
      'Shimla', // Capital city
      'Manali',
      'Kullu',
      'Kangra',
      'Solan',
      'Mandi',
      'Chamba',
      'Nahan',
      'Hamirpur',
      'Bilaspur',
      'Una',
      'Nalagarh',
      'Palampur',
      'Paonta Sahib',
      'Dalhousie',
      'Arki',
      'Sundernagar',
      'Bhuntar',
      'Rewalsar',
      'Rampur',
      'Nagrota',
      'Nurpur',
      'Baghi',
      'Chandigarh',
    ],
    JammuAndKashmir: [
      'Srinagar', // Summer capital
      'Jammu', // Winter capital
      'Anantnag',
      'Baramulla',
      'Pulwama',
      'Kulgam',
      'Kupwara',
      'Budgam',
      'Kathua',
      'Rajouri',
      'Poonch',
      'Udhampur',
      'Doda',
      'Reasi',
      'Kishtwar',
      'Jindrah',
      'Samba',
      'Akhnoor',
      'Basholi',
      'Vijaypur',
      'Billawar',
      'Nowshera',
      'R S Pura',
      'Chadoora',
      'Qazigund',
      'Varmul',
      'Kangan',
      'Trekhama',
      'Mendhar',
    ],
    Jharkhand: [
      'Ranchi', // Capital city
      'Jamshedpur',
      'Dhanbad',
      'Hazaribagh',
      'Bokaro Steel City',
      'Giridih',
      'Deoghar',
      'Chaibasa',
      'Dumka',
      'Ramgarh',
      'Jamtara',
      'Khunti',
      'Pakur',
      'Koderma',
      'Sahebganj',
      'Simdega',
      'Godda',
      'Latehar',
      'Lohardaga',
      'Garhwa',
      'Chatra',
      'Palamu',
      'West Singhbhum',
      'East Singhbhum',
    ],
    Karnataka: [
      'Bengaluru', // Capital city
      'Mysuru',
      'Mangalore',
      'Hubballi',
      'Belagavi',
      'Davangere',
      'Ballari',
      'Shimoga',
      'Tumakuru',
      'Udupi',
      'Chitradurga',
      'Bagalkot',
      'Hassan',
      'Chikkamagaluru',
      'Mandya',
      'Raichur',
      'Kolar',
      'Karwar',
      'Ramanagaram',
      'Gulbarga',
      'Bidar',
      'Haveri',
      'Yadgir',
      'Chikballapur',
      'Bijapur',
      'Davanagere',
      'Sagar',
      'Chamarajanagar',
      'Koppal',
      'Kollegal',
      'Sirsi',
      'Srirangapatna',
      'Nanjangud',
      'Vijayapura',
      'Puttur',
    ],
    Kerala: [
      'Thiruvananthapuram', // Capital city
      'Kochi',
      'Kozhikode',
      'Kollam',
      'Thrissur',
      'Alappuzha',
      'Malappuram',
      'Kannur',
      'Pathanamthitta',
      'Palakkad',
      'Kottayam',
      'Idukki',
      'Wayanad',
      'Varkala',
      'Punalur',
      'Changanassery',
      'Nellimattom',
      'Perumbavoor',
      'Attingal',
      'Muvattupuzha',
      'Adoor',
      'Vadakara',
      'Kottarakkara',
      'Cherthala',
      'Peringathur',
      'Pala',
      'Kothamangalam',
      'Koyilandy',
      'Kunnamkulam',
      'Thalassery',
    ],
    MadhyaPradesh: [
      'Bhopal', // Capital city
      'Indore',
      'Gwalior',
      'Jabalpur',
      'Ujjain',
      'Khandwa',
      'Sagar',
      'Dewas',
      'Rewa',
      'Satna',
      'Burhanpur',
      'Khargone',
      'Shivpuri',
      'Mandsaur',
      'Ratlam',
      'Chhindwara',
      'Hoshangabad',
      'Vidisha',
      'Sehore',
      'Betul',
      'Shahdol',
      'Neemuch',
      'Tikamgarh',
      'Balaghat',
      'Narsinghpur',
      'Rajgarh',
      'Chhatarpur',
      'Damoh',
      'Pithampur',
      'Dindori',
      'Mandla',
      'Harda',
      'Alirajpur',
      'Anuppur',
      'Ashok Nagar',
    ],
    Maharashtra: [
      'Mumbai', // Capital city
      'Pune',
      'Nagpur',
      'Nashik',
      'Aurangabad',
      'Thane',
      'Kolhapur',
      'Solapur',
      'Satara',
      'Amravati',
      'Ratnagiri',
      'Jalna',
      'Chandrapur',
      'Nanded',
      'Dhule',
      'Raigad',
      'Sangli',
      'Akola',
      'Palghar',
      'Bhiwandi',
      'Miraj',
      'Latur',
      'Karad',
      'Ghatkopar',
      'Dombivli',
      'Ulhasnagar',
      'Kalyan',
      'Vasai',
      'Virar',
      'Vashi',
      'Bhusawal',
      'Khamgaon',
      'Yavatmal',
      'Sindhudurg',
      'Boisar',
      'Parbhani',
      'Aurangabad',
    ],
    Manipur: [
      'Imphal', // Capital city
      'Thoubal',
      'Churachandpur',
      'Kakching',
      'Bishnupur',
      'Jiribam',
      'Senapati',
      'Ukhrul',
      'Tamenglong',
      'Noney',
      'Kangpokpi',
      'Tengnoupal',
      'Moreh',
      'Peren',
      'Khongjom',
      'Moirang',
      'Nambol',
    ],
    Meghalaya: [
      'Shillong', // Capital city
      'Tura',
      'Nongpoh',
      'Jowai',
      'Baghmara',
      'Williamnagar',
      'Mawkyrwat',
      'Resubelpara',
      'Nongstoin',
      'Cherapunjee',
      'Laban',
      'Ranikor',
      'Amirabad',
      'Dawki',
      'Pynursla',
    ],
    Mizoram: [
      'Aizawl', // Capital city
      'Lunglei',
      'Champhai',
      'Kolasib',
      'Serchhip',
      'Mamit',
      'Lawngtlai',
      'Hnahthial',
      'Siaha',
      'Kolasib',
      'Vairengte',
      'Biate',
      'Tlungvel',
      'Thingdawl',
      'Saitual',
      'Reiek',
      'Lengteng',
    ],
    Nagaland: [
      'Kohima', // Capital city
      'Dimapur',
      'Mokokchung',
      'Wokha',
      'Zunheboto',
      'Tuensang',
      'Mon',
      'Peren',
      'Kiphire',
      'Longleng',
      'Phek',
      'Chümoukedima',
      'Chizami',
      'Tseminyu',
    ],
    Odisha: [
      'Bhubaneswar', // Capital city
      'Cuttack',
      'Rourkela',
      'Sambalpur',
      'Berhampur',
      'Balasore',
      'Bargarh',
      'Angul',
      'Jagatsinghpur',
      'Dhenkanal',
      'Jharsuguda',
      'Kendrapara',
      'Kalinganagar',
      'Puri',
      'Koraput',
      'Nayagarh',
      'Khurda',
      'Malkangiri',
      'Rayagada',
      'Ganjam',
      'Bhadrak',
      'Pattamundai',
      'Phulbani',
      'Jajpur',
      'Mayurbhanj',
      'Balangir',
      'Boudh',
      'Kendujhar',
      'Sundargarh',
      'Chhatrapur',
      'Gopalpur',
    ],
    Punjab: [
      'Chandigarh', // Capital city (shared with Haryana)
      'Amritsar',
      'Ludhiana',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali',
      'Firozpur',
      'Moga',
      'Hoshiarpur',
      'Rajpura',
      'Khanna',
      'Sangrur',
      'Gurdaspur',
      'Rupnagar',
      'Faridkot',
      'Tarn Taran',
      'Muktsar',
      'Barnala',
      'Sri Muktsar Sahib',
      'Kapurthala',
      'Ajnala',
      'Samrala',
      'Zirakpur',
      'Fatehgarh Sahib',
      'Nawanshahr',
      'Phagwara',
      'Dasuya',
      'Jagraon',
      'Batala',
      'Anandpur Sahib',
      'Bilga',
      'Bassi Pathana',
    ],
    Rajasthan: [
      'Jaipur', // Capital city
      'Udaipur',
      'Jodhpur',
      'Kota',
      'Ajmer',
      'Bikaner',
      'Alwar',
      'Pali',
      'Chittorgarh',
      'Sikar',
      'Tonk',
      'Jhunjhunu',
      'Barmer',
      'Nagaur',
      'Bhilwara',
      'Hanumangarh',
      'Churu',
      'Rishabhdeo',
      'Kishangarh',
      'Sri Ganganagar',
      'Dholpur',
      'Jaisalmer',
      'Banswara',
      'Rajsamand',
      'Sawai Madhopur',
      'Dungarpur',
      'Jhalawar',
      'Baran',
      'Jalore',
      'Sirohi',
      'Merta',
      'Phalodi',
      'Makrana',
      'Kishangarh',
      'Bundi',
    ],
    Sikkim: [
      'Gangtok', // Capital city
      'Namchi',
      'Mangan',
      'Rangpo',
      'Jorethang',
      'Pakyong',
      'Singtam',
      'Ravangla',
      'Lachung',
      'Lingtam',
      'Gyalshing',
      'Melli',
      'Sombaria',
      'Tadong',
      'Sang',
    ],
    TamilNadu: [
      'Chennai', // Capital city
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tirunelveli',
      'Erode',
      'Vellore',
      'Dindigul',
      'Thanjavur',
      'Kanchipuram',
      'Cuddalore',
      'Chidambaram',
      'Karur',
      'Nagapattinam',
      'Vikrampuri',
      'Thoothukudi',
      'Kanyakumari',
      'Pudukkottai',
      'Sivakasi',
      'Virudhunagar',
      'Ramanathapuram',
      'Arakkonam',
      'Krishnagiri',
      'Tiruvannamalai',
      'Pollachi',
      'Nagercoil',
      'Namakkal',
      'Ariyalur',
      'Perambalur',
      'Kancheepuram',
      'Tiruvarur',
      'Kanchipuram',
      'Kumbakonam',
      'Mettur',
      'Sirkali',
      'Udhagamandalam (Ooty)',
    ],
    Telangana: [
      'Hyderabad', // Capital city
      'Warangal',
      'Khammam',
      'Nizamabad',
      'Karimnagar',
      'Mahabubnagar',
      'Nalgonda',
      'Ramagundam',
      'Sircilla',
      'Peddapalli',
      'Adilabad',
      'Jagitial',
      'Jangaon',
      'Medak',
      'Kamareddy',
      'Miryalaguda',
      'Malkajgiri',
      'Bodhan',
      'Sangareddy',
      'Mancherial',
      'Pochampally',
      'Kothagudem',
      'Yadagirigutta',
      'Vemulawada',
      'Tandur',
      'Khagol',
      'Jubilee Hills',
      'Secunderabad',
      'Malkajgiri',
      'Banjara Hills',
      'Ameerpet',
      'Lingampally',
      'Puranapul',
    ],
    Tripura: [
      'Agartala', // Capital city
      'Udaipur',
      'Sonamura',
      'Dharmanagar',
      'Belonia',
      'Kailashahar',
      'Ambassa',
      'Khowai',
      'Bishalgarh',
      'Sepahijala',
      'Jirania',
      'Madhupur',
      'Manu',
      'Takarjala',
      'Melaghar',
      'Bamutia',
      'Kanchanpur',
      'Jampuijala',
      'Raishyabari',
      'Simna',
      'Lalchara',
      'Chandrapur',
    ],
    Uttarakhand: [
      'Dehradun', // Capital city
      'Haridwar',
      'Nainital',
      'Rishikesh',
      'Mussoorie',
      'Haldwani',
      'Roorkee',
      'Kashipur',
      'Pithoragarh',
      'Rudrapur',
      'Kichha',
      'Almora',
      'Bageshwar',
      'Tehri',
      'Champawat',
      'Ranikhet',
      'Udham Singh Nagar',
      'Kotdwar',
      'Lohaghat',
      'Srinagar',
      'Jaspur',
      'Bhawanipur',
      'Bijnor',
      'Lansdowne',
      'Kalsi',
    ],
    UttarPradesh: [
      'Lucknow', // Capital city
      'Kanpur',
      'Varanasi',
      'Agra',
      'Allahabad (Prayagraj)',
      'Meerut',
      'Ghaziabad',
      'Moradabad',
      'Bareilly',
      'Aligarh',
      'Mathura',
      'Firozabad',
      'Saharanpur',
      'Rampur',
      'Muzaffarnagar',
      'Shahjahanpur',
      'Jaunpur',
      'Etawah',
      'Bijnor',
      'Azamgarh',
      'Unnao',
      'Amroha',
      'Sultanpur',
      'Sitapur',
      'Hardoi',
      'Bahraich',
      'Raebareli',
      'Ballia',
      'Farrukhabad',
      'Badaun',
      'Gorakhpur',
      'Jhansi',
      'Basti',
      'Hapur',
      'Deoria',
      'Chitrakoot',
      'Kannauj',
      'Kushi Nagar',
      'Sambhal',
      'Mahoba',
      'Shamli',
      'Mirzapur',
      'Prayagpur',
      'Kanshiram Nagar',
      'Lalitpur',
    ],
    WestBengal: [
      'Kolkata', // Capital city
      'Howrah',
      'Durgapur',
      'Asansol',
      'Siliguri',
      'Malda',
      'Jalpaiguri',
      'Berhampore',
      'Burdwan',
      'Kalyani',
      'Bhatpara',
      'Haldia',
      'Krishnanagar',
      'Cooch Behar',
      'Rajarhat',
      'Chandannagar',
      'Kolkata Suburban District',
      'Bishnupur',
      'Alambazar',
      'Kamarhati',
      'Dankuni',
      'Baranagar',
      'Naihati',
      'Taki',
      'Raiganj',
      'Bongaon',
      'Bankura',
      'Purulia',
      'Bishnupur',
      'Suri',
      'Jhargram',
      'Medinipur',
      'Chinsurah',
      'Madarhat',
      'Burdwan',
      'Santipur',
    ],
    AndamanAndNicobarIslands: [
      'Port Blair', // Capital city
      'Havelock Island',
      'Neil Island',
      'Diglipur',
      'Baratang Island',
      'Mayabunder',
      "Ritchie's Archipelago",
      'Campbell Bay',
      'Katchal Island',
      'Little Andaman Island',
      'Car Nicobar',
      'Nancowry',
      'Great Nicobar',
      'Ross Island',
      'Viper Island',
      'Long Island',
      'Swaraj Dweep (formerly Havelock)',
    ],
    DadraAndNagarHaveli: [
      'Silvassa', // Capital city
      'Dadra',
      'Naroli',
      'Amli',
      'Saily',
      'Khanvel',
      'Vasona',
    ],
    DamanAndDiu: [
      'Daman', // Capital city
      'Diu',
      'Nagoa',
      'Moti Daman',
      'Fudam',
      'Devka Beach',
      'Vanakbara',
    ],
    Delhi: [
      'New Delhi', // Capital city
      'Old Delhi', // Historic part of Delhi
      'Janakpuri',
      'Rohini',
      'Dwarka',
      'Vikaspuri',
      'Pitampura',
      'Karol Bagh',
      'Connaught Place',
      'Saket',
      'Green Park',
      'Lajpat Nagar',
      'Greater Kailash',
      'Chandni Chowk',
      'Kalkaji',
      'Hauz Khas',
      'Delhi Cantonment',
      'Moti Nagar',
      'Rajouri Garden',
      'Shahdara',
      'Okhla',
      'Vasant Kunj',
      'Pitampura',
      'Raj Nagar',
      'Burari',
      'Dwarka Sector 21',
      'Sarai Kale Khan',
    ],
    Lakshadweep: [
      'Kavaratti', // Capital city
      'Agatti',
      'Minicoy',
      'Amini',
      'Kadmat',
      'Chetlat',
      'Kiltan',
      'Andrott',
      'Bitra',
      'Kalapeni',
      'Suheli Par',
      'Maliku Atoll',
    ],
    Puducherry: [
      'Puducherry', // Capital city
      'Auroville',
      'Cuddalore',
      'Karaikal',
      'Mahe',
      'Yanam',
    ],
  },

  // Method to get cities by state
  getCitiesByState(state: string): string[] {
    // Sanitize state name to match the object key format
    const sanitizedState = state
      .replace(/\s+/g, '') // Remove spaces
      .replace(/and/g, 'And') // Capitalize 'and' to 'And'
      .replace(/-/g, '') // Remove hyphens
      .replace(/\b\w/g, (char) => char.toUpperCase()); // Capitalize first letter of each word (for states like 'Uttar Pradesh')

    // Cast sanitized state to the correct type
    return this.cities[sanitizedState as State] || [];
  },
};